version = 0.1

[default.deploy.parameters]
stack_name = "returnguard-stack"
resolve_s3 = true
s3_prefix = "returnguard-stack"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AlertEmail=\"fairytale9788@gmail.com\""
image_repositories = []

[default.global.parameters]
region = "us-west-2"
